@base_address = http://localhost:3000/api/people

POST {{base_address}}
Content-Type: application/json

{
    "firstName": "이",
    "lastName": "창호"
}


###
GET {{base_address}}

###
GET {{base_address}}/15

###
PUT {{base_address}}/15
Content-Type: application/json

{
    "id": 15,
    "firstName": "창호2",
    "lastName": "최"
}

###
DELETE {{base_address}}/15